name: 'Setup Task'
description: 'Download Task and add it to the PATH'
author: 'Arduino'
inputs:
  version:
    description: 'Version to use. Example: 3.4.2'
    default: '3.x'
  repo-token:
    description: "Token with permissions to do repo things"

runs:
  using: 'node12'
  main: 'lib/main.js'
