name: 'Arduino Libraries - Compile Examples'
description: 'Compiles all the examples included in the library'
inputs:
  cli-version:
    description: 'Version of arduino-cli to use when builing'
    default: 'latest'
  fqbn:
    description: 'Full qualified board name, with Boards Manager URL if needed'
    default: 'arduino:avr:uno'
  libraries:
    description: 'List of library dependencies to install (space separated)'
    default: ''
  github-token:
    description: 'GitHub access token used to get information from the GitHub API. Only needed if you are using the size report features with private repositories.'
    default: ''
  size-report-sketch:
    description: 'Name of the sketch used to compare memory usage change'
    default: ''
  enable-size-deltas-report:
    description: 'Set to true to cause the action to determine the change in memory usage for the size-reports-sketch'
    default: false
  size-deltas-report-folder-name:
    description: 'Folder to save the memory usage change report to'
    default: 'size-deltas-reports'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cli-version }}
    - ${{ inputs.fqbn }}
    - ${{ inputs.libraries }}
    - ${{ inputs.github-token }}
    - ${{ inputs.size-report-sketch }}
    - ${{ inputs.enable-size-deltas-report }}
    - ${{ inputs.size-deltas-report-folder-name }}
