name: 'Arduino Libraries - Compile Examples'
description: 'Compiles all the examples included in the library'
inputs:
  cli-version:
    description: 'Version of arduino-cli to use when builing'
    default: 'latest'
  fqbn:
    description: 'Full qualified board name, with Boards Manager URL if needed'
    default: 'arduino:avr:uno'
  libraries:
    description: 'YAML-format list of library dependencies to install'
    default: '- source-path: ./'
  platforms:
    description: 'YAML-format list of platform dependencies to install'
    default: ''
  sketch-paths:
    description: 'List of paths containing sketches to compile.'
    default: 'examples'
  verbose:
    description: 'Set to true to show verbose output in the log'
    default: false
  sketches-report-path:
    description: 'Path in which to save a JSON formatted file containing data from the sketch compilations'
    default: 'size-deltas-reports'
  github-token:
    description: 'GitHub access token used to get information from the GitHub API. Only needed if you are using the size deltas report feature with a private repository.'
    default: ''
  enable-size-deltas-report:
    description: 'Set to true to cause the action to determine the change in memory usage of the compiled sketches between the head and base refs of a PR'
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
