name: libraries/report-size-deltas workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8.2'

      - name: Lint with flake8
        run: |
          pip install --quiet flake8
          pip install --quiet pep8-naming
          flake8 --show-source "$GITHUB_WORKSPACE/libraries/report-size-deltas"

      - name: Run Python unit tests
        run: |
          export PYTHONPATH="$GITHUB_WORKSPACE/libraries/report-size-deltas"
          python -m unittest discover "$GITHUB_WORKSPACE/libraries/report-size-deltas/tests"
