name: libraries/spell-check workflow

on:
  push:
    paths:
      - ".github/workflows/libraries_spell-check.yml"
      - "libraries/spell-check/**.sh"
      - "libraries/spell-check/test/**"
  pull_request:
    paths:
      - ".github/workflows/libraries_spell-check.yml"
      - "libraries/spell-check/**.sh"
      - "libraries/spell-check/test/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Run tests 
        run: |
          pip3 --quiet --quiet install codespell
          git clone --quiet https://github.com/bats-core/bats-core.git
          cd bats-core
          git fetch --tags
          # Checkout the latest tag
          git checkout --quiet $(git describe --tags `git rev-list --tags --max-count=1`)
          sudo ./install.sh "/usr/local" > /dev/null
          cd "$GITHUB_WORKSPACE/libraries/spell-check"
          bats "./test"

  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ShellCheck 
        uses: azohra/shell-linter@v0.3.0
        with:
          path: "libraries/spell-check"

  shfmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check shell script formatting
        # https://github.com/mvdan/sh
        run: docker run --volume "$GITHUB_WORKSPACE/libraries/spell-check":/mnt --workdir /mnt mvdan/shfmt:latest -w .

      - name: Formatting diff
        run: git diff --color --exit-code
