name: libraries/spell-check workflow

on:
  push:
    paths:
      - ".github/workflows/libraries_spell-check.yml"
      - "libraries/spell-check/**.sh"
  pull_request:
    paths:
      - ".github/workflows/libraries_spell-check.yml"
      - "libraries/spell-check/**.sh"

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ShellCheck 
        uses: azohra/shell-linter@v0.3.0
        with:
          path: "libraries/spell-check"

  shfmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check shell script formatting
        # https://github.com/mvdan/sh
        run: docker run --volume "$GITHUB_WORKSPACE/libraries/spell-check":/mnt --workdir /mnt mvdan/shfmt:latest -w .

      - name: Formatting diff
        run: git diff --color --exit-code
