name: libraries/report-size-trends workflow

on:
  pull_request:
    paths:
      - '.github/workflows/libraries_report-size-trends.yml'
      - 'libraries/report-size-trends/**'

  push:
    paths:
      - '.github/workflows/libraries_report-size-trends.yml'
      - 'libraries/report-size-trends/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --requirement "$GITHUB_WORKSPACE/libraries/report-size-trends/reportsizetrends/tests/requirements.txt"

      - name: Lint with flake8
        run: |
          pip install --quiet flake8
          pip install --quiet pep8-naming
          flake8 --config "$GITHUB_WORKSPACE/libraries/report-size-trends/reportsizetrends/.flake8" --show-source "$GITHUB_WORKSPACE/libraries/report-size-trends/reportsizetrends"

      - name: Run Python unit tests and report code coverage
        run: |
          export PYTHONPATH="$GITHUB_WORKSPACE/libraries/report-size-trends/reportsizetrends"
          coverage run --source="$GITHUB_WORKSPACE/libraries/report-size-trends/reportsizetrends" --module pytest "$GITHUB_WORKSPACE/libraries/report-size-trends/reportsizetrends/tests"
          # Display code coverage report in workflow run log
          coverage report

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
