name: Spell Check

on: [push, pull_request]

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Spell check
        uses: ./libraries/spell-check
        with:
          ignore-words-list: etc/codespell-ignore-words-list.txt
          skip-paths: ./libraries/spell-check/test/testdata,./setup-taskfile/node_modules,./setup-taskfile/package-lock.json
